#!/bin/bash

FILES=( $(find images/debug -name '*.jpg') )


FILE_COUNT=${#FILES[@]}

for ((i=0 ; i< $FILE_COUNT; i++))
do
   nr=$((i+1))
   echo "iterate: $nr"
   echo "filename: ${FILES[$i]}"
   echo "ON"
   echo "${FILES[$i]}"
   ./Debug/HIT2600NLDB ${FILES[$i]}
   echo "=============================="
done
